services:
  postgres:
    image: postgres
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: mirza
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MirzaAbdijanovic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d MirzaAbdijanovic -U mirza"]
      interval: 2s
      timeout: 2s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: PGAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
  laravel:
    build:
      dockerfile: ./Dockerfile
    container_name: Laravel
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    environment:
      SERVER_NAME: ":80"
    tty: true
volumes:
  postgres_data: